### PR TITLE
Fix C string to wstring conversion

### PR DESCRIPTION
**Pull request by wheremyfoodat**

### CODE REVIEW

**Comment by wheremyfoodat** [comment]
(I think this will break horribly with unicode chars but that's for later. Might be best to make the API work with another C string type like wchar_t if std::filesystem is unusable)

**Comment by wheremyfoodat** [comment]
Further fixes need https://github.com/hydra-emu/core/pull/4 merged

**Comment by OFFTKP** [comment]
Looks like you fixed linux build too, happy panda.

**Comment by OFFTKP** [comment]
lgtm, if you want to add something go ahead otherwise I'll merge

**Comment by wheremyfoodat** [comment]
Merg

**Pull request merged**
